version: '3'
services:
  next:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3002:3003'
    environment:
      - PORT=3003
    command: npm run dev -- -p 3003
    volumes:
      - .:/app  # ← ★「/usr/src/app」から「/app」に修正！
      # - /usr/src/app/node_modules
