services:
  next:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
    command: npm run dev -- -p 3003
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
